name: CI

on: [push, pull_request_target]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ROBO_VERSION: [ "4.0", "5.0" ]
        PHP_VERSION: [ "8.2", "8.3", "8.0", "8.1" ]
        exclude:
          - ROBO_VERSION: "5.0"
            PHP_VERSION: [ "8.0", "8.1" ]

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          command: "require consolidation/robo:~${{ matrix.ROBO_VERSION }}"
          php_version: ${{ matrix.PHP_VERSION }}
          version: 2
      - uses: php-actions/phpunit@v3
