name: CI

on: [push, pull_request_target]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PHP_VERSION: [ "8.0", "8.1" ]

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}
          version: 2
      - uses: php-actions/phpunit@v3
